"""likes seed

Revision ID: bf064bd66572
Revises: d36811e377e2
Create Date: 2020-12-02 00:43:47.834419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table


# revision identifiers, used by Alembic.
revision = 'bf064bd66572'
down_revision = 'd36811e377e2'
branch_labels = None
depends_on = None


def upgrade():
    like = table('likes',
        sa.Column('id', sa.Integer()),
        sa.Column('post_id', sa.Integer()),
        sa.Column('photo_id', sa.Integer()),
        sa.Column('user_id', sa.Integer()),
    )

    op.bulk_insert(like, [
        {
            'post_id': 1,
            'user_id': 5
        },
        {
            'post_id': 2,
            'user_id': 10
        },
        {
            'post_id': 2,
            'user_id': 7
        },
        {
            'post_id': 2,
            'user_id': 1
        },
        {
            'post_id': 2,
            'user_id': 6
        },
        {
            'post_id': 2,
            'user_id': 3
        },
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tags')
    op.drop_table('tags')
    op.drop_table('likes')
    op.drop_table('photos')
    op.drop_table('comments')
    op.drop_table('followers')
    op.drop_table('transactions')
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###
