"""comments seed

Revision ID: 2f3f7ac68e1f
Revises: 72efc2b0af9c
Create Date: 2020-12-02 00:34:05.806492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table


# revision identifiers, used by Alembic.
revision = '2f3f7ac68e1f'
down_revision = '72efc2b0af9c'
branch_labels = None
depends_on = None


def upgrade():
    comment = table('comments',
        sa.Column('id', sa.Integer()),
        sa.Column('body', sa.String()),
        sa.Column('sender_id', sa.Integer()),
        sa.Column('recipient_id', sa.Integer()),
        sa.Column('transaction_id', sa.Integer()),
    )

    op.bulk_insert(comment, [
        {
            'body': 'I love your work!!',
            'sender_id': 1,
            'transaction_id': 1
        },
        {
            'body': 'You are amazing!',
            'sender_id': 4,
            'transaction_id': 2
        },
        {
            'body': 'Just wanted to show my support',
            'sender_id': 6,
            'transaction_id': 3
        },
        {
            'body': 'I\'m a huge fan. Keep it up!',
            'sender_id': 8,
            'transaction_id': 4
        },
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tags')
    op.drop_table('tags')
    op.drop_table('likes')
    op.drop_table('photos')
    op.drop_table('comments')
    op.drop_table('followers')
    op.drop_table('transactions')
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###
