"""locations seed

Revision ID: f450bb3a3292
Revises: 0192e778c20a
Create Date: 2020-12-09 23:23:13.882671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table


# revision identifiers, used by Alembic.
revision = 'f450bb3a3292'
down_revision = '0192e778c20a'
branch_labels = None
depends_on = None


def upgrade():
    location = table('locations',
        sa.Column('id', sa.Integer(), autoincrement=True),
        sa.Column('user_id', sa.Integer()),
        sa.Column('lat', sa.Numeric()),
        sa.Column('lng', sa.Numeric())
    )
    op.bulk_insert(location, [
        {
            'user_id': 2,
            'lat': 47.608013,
            'lng': -122.335167
        },
        {
            'user_id': 3,
            'lat': 40.730610,
            'lng': -73.935242,
        },
        {
            'user_id': 4,
            'lat': 37.773972,
            'lng': -122.431297,
        },
        {
            'user_id': 5,
            'lat': 48.1167,
            'lng': -53.7333,
        }
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tags')
    op.drop_table('tags')
    op.drop_table('likes')
    op.drop_table('photos')
    op.drop_table('comments')
    op.drop_table('followers')
    op.drop_table('transactions')
    op.drop_table('posts')
    op.drop_table('locations')
    op.drop_table('users')
    # ### end Alembic commands ###
