"""tags seed

Revision ID: 4d055336482a
Revises: bf064bd66572
Create Date: 2020-12-02 00:46:47.950999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table


# revision identifiers, used by Alembic.
revision = '4d055336482a'
down_revision = 'bf064bd66572'
branch_labels = None
depends_on = None


def upgrade():
    tag = table('tags',
        sa.Column('id', sa.Integer()),
        sa.Column('name', sa.String()),
    )

    op.bulk_insert(tag, [
        {
            'name': 'Art'
        },
        {
            'name': 'Blogging'
        },
        {
            'name': 'Dance & Theatre'
        },
        {
            'name': 'Design'
        },
        {
            'name': 'Food & Drink'
        },
        {
            'name': 'Lifestyle'
        },
        {
            'name': 'Photography'
        },
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tags')
    op.drop_table('tags')
    op.drop_table('likes')
    op.drop_table('photos')
    op.drop_table('comments')
    op.drop_table('followers')
    op.drop_table('transactions')
    op.drop_table('posts')
    op.drop_table('locations')
    op.drop_table('users')
    # ### end Alembic commands ###
