"""user_tags seed

Revision ID: 0192e778c20a
Revises: 4d055336482a
Create Date: 2020-12-02 00:50:36.145725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table


# revision identifiers, used by Alembic.
revision = '0192e778c20a'
down_revision = '4d055336482a'
branch_labels = None
depends_on = None


def upgrade():
    user_tags = table('user_tags',
        sa.Column('id', sa.Integer()),
        sa.Column('tag_id', sa.Integer()),
        sa.Column('user_id', sa.Integer()),
    )

    op.bulk_insert(user_tags, [
        {
            'tag_id': 1,
            'user_id': 1,
        },
        {
            'tag_id': 7,
            'user_id': 2,
        },
        {
            'tag_id': 7,
            'user_id': 3,
        },
        {
            'tag_id': 7,
            'user_id': 4,
        },
        {
            'tag_id': 7,
            'user_id': 6,
        },
        {
            'tag_id': 2,
            'user_id': 7,
        },
        {
            'tag_id': 3,
            'user_id': 8,
        },
        {
            'tag_id': 5,
            'user_id': 9,
        },
        {
            'tag_id': 6,
            'user_id': 10,
        },
        {
            'tag_id': 3,
            'user_id': 13,
        },
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tags')
    op.drop_table('tags')
    op.drop_table('likes')
    op.drop_table('photos')
    op.drop_table('comments')
    op.drop_table('followers')
    op.drop_table('transactions')
    op.drop_table('posts')
    op.drop_table('locations')
    op.drop_table('users')
    # ### end Alembic commands ###
