"""photos seed

Revision ID: d36811e377e2
Revises: 2f3f7ac68e1f
Create Date: 2020-12-02 00:40:55.380747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table


# revision identifiers, used by Alembic.
revision = 'd36811e377e2'
down_revision = '2f3f7ac68e1f'
branch_labels = None
depends_on = None


def upgrade():
    photo = table('photos',
        sa.Column('id', sa.Integer()),
        sa.Column('pic_url', sa.String()),
        sa.Column('user_id', sa.Integer()),
    )

    # op.bulk_insert(follower, [
    #     {
    #         'pic_url': ,
    #         'user_id': 1
    #     },
    # ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tags')
    op.drop_table('tags')
    op.drop_table('likes')
    op.drop_table('photos')
    op.drop_table('comments')
    op.drop_table('followers')
    op.drop_table('transactions')
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###
