"""posts seed

Revision ID: dd9a6b4edf0c
Revises: 6e9a19377dc3
Create Date: 2020-12-02 00:20:00.594386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table


# revision identifiers, used by Alembic.
revision = 'dd9a6b4edf0c'
down_revision = '6e9a19377dc3'
branch_labels = None
depends_on = None


def upgrade():
    post = table('posts',
        sa.Column('id', sa.Integer()),
        sa.Column('body', sa.String()),
        sa.Column('user_id', sa.Integer()),
    )

    op.bulk_insert(post,
    [
        {
            'body': 'Hey guys! Really excited to join kafei and interact with you all!',
            'user_id': 1
        },
        {
            'body': 'Thanks for all the support. New content coming soon, so keep your eyes peeled!',
            'user_id': 3
        },
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tags')
    op.drop_table('tags')
    op.drop_table('likes')
    op.drop_table('photos')
    op.drop_table('comments')
    op.drop_table('followers')
    op.drop_table('transactions')
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###
