"""followers seed

Revision ID: 72efc2b0af9c
Revises: 9b23b41a0ad3
Create Date: 2020-12-02 00:29:44.242054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table


# revision identifiers, used by Alembic.
revision = '72efc2b0af9c'
down_revision = '9b23b41a0ad3'
branch_labels = None
depends_on = None


def upgrade():
    follower = table('followers',
        sa.Column('id', sa.Integer()),
        sa.Column('follower_id', sa.Integer()),
        sa.Column('followed_id', sa.Integer()),
    )

    op.bulk_insert(follower, [
        {
            'follower_id': 1,
            'followed_id': 2,
        },
        {
            'follower_id': 3,
            'followed_id': 2,
        },
        {
            'follower_id': 5,
            'followed_id': 1,
        },
        {
            'follower_id': 4,
            'followed_id': 1,
        },
        {
            'follower_id': 12,
            'followed_id': 2,
        },
        {
            'follower_id': 3,
            'followed_id': 5,
        },
        {
            'follower_id': 7,
            'followed_id': 1,
        },
        {
            'follower_id': 9,
            'followed_id': 2,
        },
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tags')
    op.drop_table('tags')
    op.drop_table('likes')
    op.drop_table('photos')
    op.drop_table('comments')
    op.drop_table('followers')
    op.drop_table('transactions')
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###
