"""transactions seed

Revision ID: 9b23b41a0ad3
Revises: dd9a6b4edf0c
Create Date: 2020-12-02 00:24:56.460417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table


# revision identifiers, used by Alembic.
revision = '9b23b41a0ad3'
down_revision = 'dd9a6b4edf0c'
branch_labels = None
depends_on = None


def upgrade():
    transaction = table('transactions',
        sa.Column('id', sa.Integer()),
        sa.Column('amount', sa.Integer()),
        sa.Column('sender_id', sa.Integer()),
        sa.Column('recipient_id', sa.Integer()),
    )

    op.bulk_insert(transaction,
    [
        {
            'amount': 2,
            'sender_id': 1,
            'recipient_id': 2
        },
        {
            'amount': 5,
            'sender_id': 4,
            'recipient_id': 2
        },
        {
            'amount': 1,
            'sender_id': 6,
            'recipient_id': 1
        },
        {
            'amount': 4,
            'sender_id': 8,
            'recipient_id': 6
        },
        {
            'amount': 10,
            'sender_id': 9,
            'recipient_id': 2
        },
        {
            'amount': 2,
            'sender_id': 12,
            'recipient_id': 1
        },
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tags')
    op.drop_table('tags')
    op.drop_table('likes')
    op.drop_table('photos')
    op.drop_table('comments')
    op.drop_table('followers')
    op.drop_table('transactions')
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###
